### ISSUE TITLE
how does one reinit the editor ?

### ISSUE THREAD

**Issue by phil123456** [stewieoO/angular-tinymce#55]
Hello,

as I use the editor in ngx-tab it does not work (while it works outside of it)

I thought I could reinit the editor when the tab is clicked

but I cant find any documentation on how to do this

thanks

**Comment by siegerx3** [comment]
Hi, sorry i've been a bit busy the past days. I will take a look at this later this night when i'm back home!
But for now try checking how to reninit the official tinymce js package and see if you can already do that with this package.

**Comment by phil123456** [comment]
I now use CKEditor

**Comment by siegerx3** [comment]
Ok, but just for the information, you can get the component with `ViewChild` and from there get the instance.
