### ISSUE TITLE
skin_url doesn't work on aot builds

### ISSUE THREAD

**Issue by ktriek** [stewieoO/angular-tinymce#6]
Changing  `skin_url` doesn't work with angular-cli ng build when using the  --aot flag and always returns the default  `skin_url: '/assets/tinymce/skins/lightgray'`

**Comment by rejayi-experion** [comment]
provide it in angular-cli.json as    
  "styles": [
        "../node_modules/tinymce/skins/lightgray/skin.min.css",
        "../node_modules/tinymce/skins/lightgray/content.min.css",
]
